In [1]:
import numpy as np 
import pandas as pd
import math

# plots
import matplotlib.pyplot as plt
#import seaborn as sns
%matplotlib inline

In [2]:
filenames = ['properties/properati-AR-2016-03-01-properties-sell-six_months.csv',
            'properties/properati-AR-2016-04-01-properties-sell.csv',
            'properties/properati-AR-2016-05-01-properties-sell.csv',
            'properties/properati-AR-2016-06-01-properties-sell.csv',
            'properties/properati-AR-2016-07-01-properties-sell.csv',
            'properties/properati-AR-2016-08-01-properties-sell.csv',
            'properties/properati-AR-2016-09-01-properties-sell.csv',
            'properties/properati-AR-2016-10-01-properties-sell.csv',
            'properties/properati-AR-2016-11-01-properties-sell.csv',
            'properties/properati-AR-2016-12-01-properties-sell.csv', 
            'properties/properati-AR-2017-01-01-properties-sell.csv',
            'properties/properati-AR-2017-02-01-properties-sell.csv',
            'properties/properati-AR-2017-08-01-properties-sell-six_months.csv']

dataframes = []
for filename in filenames:
    dataframes.append(pd.read_csv(filename))

# SAQUE ESTO PARA HACER LA REGRESION A PARTIR DEL 2DO SEMESTRE DEL 2016
#dataframes.append(pd.read_csv('properties/properati-AR-2015-07-01-properties-sell.csv', skiprows=[81550]))
#dataframes.append(pd.read_csv('properties/properati-AR-2015-08-01-properties-sell.csv', skiprows=[75032]))
#dataframes.append(pd.read_csv('properties/properati-AR-2015-09-01-properties-sell.csv', skiprows=[54374]))
#dataframes.append(pd.read_csv('properties/properati-AR-2015-12-01-properties-sell.csv', skiprows=[101832]))
#Uno los dataframe
metadata = pd.DataFrame()
for dataframe in dataframes:
    metadata = pd.concat([metadata, dataframe]).drop_duplicates().reset_index(drop=True)


In [3]:
data = metadata.loc[(metadata.state_name.str.contains('Buenos Aires')) | (metadata.state_name.str.contains\
                ('Capital Federal'))  | (metadata.state_name.str.contains\
                ('Bs.As') ),:]
data.shape
# 1.283.741 entries antes, ahora 242290

(242290, 27)

In [4]:
test = pd.read_csv('properties/properati_dataset_testing_noprice.csv')
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14166 entries, 0 to 14165
Data columns (total 17 columns):
id                         14166 non-null int64
created_on                 14166 non-null object
property_type              14166 non-null object
operation                  14166 non-null object
place_name                 14166 non-null object
place_with_parent_names    14166 non-null object
country_name               14166 non-null object
state_name                 14166 non-null object
lat-lon                    10487 non-null object
lat                        10487 non-null float64
lon                        10487 non-null float64
surface_total_in_m2        11853 non-null float64
surface_covered_in_m2      13005 non-null float64
floor                      1368 non-null float64
rooms                      7500 non-null float64
expenses                   2543 non-null object
description                14166 non-null object
dtypes: float64(6), int64(1), object(10)
memory usage: 1

In [5]:
test_visualiz = test.loc[:,['state_name', 'id']].groupby('state_name').agg(np.size)
test_visualiz.head(10)

id
state_name                    
Bs.As. G.B.A. Zona Norte     2
Bs.As. G.B.A. Zona Oeste  3101
Bs.As. G.B.A. Zona Sur    2215
Buenos Aires Interior        1
Capital Federal           8847

In [6]:
data['state_name'].tail(10)

296467        Bs.As. G.B.A. Zona Norte
296468        Bs.As. G.B.A. Zona Norte
296469        Bs.As. G.B.A. Zona Norte
296470        Bs.As. G.B.A. Zona Norte
296471        Bs.As. G.B.A. Zona Norte
296472                 Capital Federal
296473        Bs.As. G.B.A. Zona Norte
296474                 Capital Federal
296475    Buenos Aires Costa Atlántica
296476                 Capital Federal
Name: state_name, dtype: object

In [8]:
# Depuración del set de test
#Completo los valores NaN con promedios para realizar la predicción
import calendar 
prom_surface_total_in_m2 = test['surface_total_in_m2'].mean()
prom_surface_covered_in_m2 = test['surface_covered_in_m2'].mean()
prom_lat = test['lat'].mean()
prom_lon = test['lon'].mean()

test_float = test
test_float['surface_total_in_m2'].fillna(prom_surface_total_in_m2, inplace=True)
test_float['surface_covered_in_m2'].fillna(prom_surface_covered_in_m2, inplace=True)
test_float['lat'].fillna(prom_lat, inplace=True)
test_float['lon'].fillna(prom_lon, inplace=True)

test_float['fecha'] = pd.to_datetime(test_float['created_on'])
test_float['anio'] = test_float['fecha'].map(lambda x:x.year)
test_float['mes'] = test_float['fecha'].map(lambda x:x.month)

test_float.head(100)

id  created_on property_type operation             place_name  \
0      3632  2017-08-24  departamento     venta          Puerto Madero   
1      3633  2017-08-25  departamento     venta  Buenos Aires Interior   
2   2263404  2017-08-01  departamento     venta           Palermo Soho   
3   2263405  2017-08-01  departamento     venta              Chacarita   
4   2263406  2017-08-01  departamento     venta              Chacarita   
5   2263407  2017-08-01  departamento     venta              Chacarita   
6   2263408  2017-08-01  departamento     venta              Chacarita   
7   2263409  2017-08-01  departamento     venta              Chacarita   
8   2263410  2017-08-01  departamento     venta             Colegiales   
9   2263411  2017-08-01  departamento     venta                Almagro   
10  2263412  2017-08-01  departamento     venta                Almagro   
11  2263413  2017-08-01  departamento     venta                Almagro   
12  2263415  2017-08-01  departamento     venta          Puerto Madero   
13  2263416  2017-08-01  departamento     venta               Belgrano   
14  2263417  2017-08-01  departamento     venta           Villa Crespo   
15  2263418  2017-08-01  departamento     venta           Villa Crespo   
16  2263419  2017-08-01  departamento     venta           Villa Crespo   
17  2263420  2017-08-01  departamento     venta           Villa Crespo   
18  2263421  2017-08-01  departamento     venta           Villa Crespo   
19  2263422  2017-08-01  departamento     venta           Villa Crespo   
20  2263423  2017-08-01  departamento     venta           Villa Crespo   
21  2263424  2017-08-01  departamento     venta           Villa Crespo   
22  2263425  2017-08-01  departamento     venta           Villa Crespo   
23  2263426  2017-08-01  departamento     venta           Villa Crespo   
24  2263427  2017-08-01  departamento     venta           Villa Crespo   
25  2263428  2017-08-01  departamento     venta           Villa Crespo   
26  2263429  2017-08-01  departamento     venta           Villa Crespo   
27  2263430  2017-08-01  departamento     venta           Villa Crespo   
28  2263431  2017-08-01  departamento     venta           Villa Crespo   
29  2263432  2017-08-01  departamento     venta           Villa Crespo   
..      ...         ...           ...       ...                    ...   
70  2264183  2017-08-01  departamento     venta        Capital Federal   
71  2264189  2017-08-01  departamento     venta               Belgrano   
72  2264198  2017-08-01          casa     venta               La Plata   
73  2264199  2017-08-01            ph     venta               La Plata   
74  2264206  2017-08-01  departamento     venta        Capital Federal   
75  2264212  2017-08-01  departamento     venta        Capital Federal   
76  2264215  2017-08-01  departamento     venta        Capital Federal   
77  2264218  2017-08-01  departamento     venta        Capital Federal   
78  2264219  2017-08-01  departamento     venta                Palermo   
79  2264221  2017-08-01  departamento     venta        Capital Federal   
80  2264227  2017-08-01  departamento     venta        Capital Federal   
81  2264229  2017-08-01  departamento     venta                Palermo   
82  2264234  2017-08-01  departamento     venta        Capital Federal   
83  2264240  2017-08-01  departamento     venta               La Plata   
84  2264242  2017-08-01  departamento     venta               Belgrano   
85  2264248  2017-08-01  departamento     venta                  Boedo   
86  2264249  2017-08-01  departamento     venta                Palermo   
87  2264259  2017-08-01  departamento     venta           Palermo Soho   
88  2264265  2017-08-01  departamento     venta        Capital Federal   
89  2264270  2017-08-01  departamento     venta               Belgrano   
90  2264272  2017-08-01            ph     venta               Banfield   
91  2264274  2017-08-01  departamento     venta               Recoleta   
92  2264284  

In [41]:
#FILTRO LOS DATOS ANOMALOS

data_float = data.loc[:, ['price_aprox_usd', 'surface_total_in_m2', 'surface_covered_in_m2',\
                           'lat', 'lon']].dropna()

#filtro
data_float = \
data_float.loc[((data_float.surface_total_in_m2 >= 0.0) & (data_float.surface_total_in_m2 <= 1000000.0)) & \
               ((data_float.surface_covered_in_m2 >= 0.0) & (data_float.surface_covered_in_m2 <= 50000000.0)), :]


data_float.shape
#(68586, 6)

(104604, 5)

In [42]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5, init='k-means++', )
points = kmeans.fit_transform(data_float)
#kmeans.cluster_centers_
points

array([[  2.79026919e+05,   4.05912216e+05,   5.73973885e+05,
          5.81934188e+06,   1.87165587e+06],
       [  3.20973313e+05,   1.00591223e+06,   2.60268188e+04,
          6.41934201e+06,   2.47165594e+06],
       [  2.90973473e+05,   9.75912326e+05,   3.97472614e+03,
          6.38934218e+06,   2.44165602e+06],
       ..., 
       [  2.55973438e+05,   9.40912304e+05,   3.89736360e+04,
          6.35434215e+06,   2.40665601e+06],
       [  2.55973500e+05,   9.40912332e+05,   3.89737311e+04,
          6.35434219e+06,   2.40665603e+06],
       [  2.89473474e+05,   9.74412326e+05,   5.47442602e+03,
          6.38784218e+06,   2.44015602e+06]])

In [43]:
len(kmeans.labels_)

104604

In [13]:
#y_pred = KMeans(n_clusters=3, random_state=random_state).fit_predict(X_varied)

In [44]:
kmeans.cluster_centers_

array([[  4.20973294e+05,   3.24612408e+02,   2.03190377e+02,
         -3.47066255e+01,  -5.85101998e+01],
       [  1.10591219e+06,   4.73844690e+02,   3.42495724e+02,
         -3.45612937e+01,  -5.84498230e+01],
       [  1.26026388e+05,   1.31743168e+02,   7.84396894e+01,
         -3.51094409e+01,  -5.84093428e+01],
       [  6.51934043e+06,   4.19508511e+03,   2.32551064e+03,
         -3.45608812e+01,  -5.84414327e+01],
       [  2.57165584e+06,   8.20066929e+02,   5.91931102e+02,
         -3.46257617e+01,  -5.84499580e+01]])

In [47]:
kmeans = KMeans(n_clusters=3, init='k-means++', )
kmeans.fit(data_float)
print kmeans.score(data_float)


-2.92216444445e+15


In [51]:
kmeans = KMeans(n_clusters=4, init='k-means++', )
kmeans.fit(data_float)
print kmeans.score(data_float)


-1.83760416745e+15


In [52]:
kmeans = KMeans(n_clusters=5, init='k-means++', )
kmeans.fit(data_float)
print kmeans.score(data_float)

-1.26697646675e+15


In [53]:
kmeans = KMeans(n_clusters=6, init='k-means++', )
points = kmeans.fit_transform(data_float)
print kmeans.score(data_float)


-8.45624251813e+14


In [54]:
kmeans = KMeans(n_clusters=7, init='k-means++', )
points = kmeans.fit_transform(data_float)
print kmeans.score(data_float)


-6.67627524676e+14


In [55]:
kmeans = KMeans(n_clusters=8, init='k-means++', )
points = kmeans.fit_transform(data_float)
print kmeans.score(data_float)


-5.23437339839e+14


In [56]:
kmeans = KMeans(n_clusters=9, init='k-means++', )
points = kmeans.fit_transform(data_float)
print kmeans.score(data_float)


-4.18081585803e+14


In [57]:
kmeans = KMeans(n_clusters=3, init='k-means++', )
points = kmeans.fit_transform(data_float)
points

array([[  5.35200724e+05,   2.31350136e+06,   1.43101971e+05],
       [  6.47996472e+04,   2.91350146e+06,   7.43101853e+05],
       [  3.47997686e+04,   2.88350156e+06,   7.13101961e+05],
       ..., 
       [  2.14308707e+02,   2.84850154e+06,   6.78101936e+05],
       [  2.38591945e+02,   2.84850156e+06,   6.78101970e+05],
       [  3.32997806e+04,   2.88200156e+06,   7.11601962e+05]])

In [58]:
len(points)

104604

In [ ]:
d = {'col1': points[:,0], 'col2': points[:,1], 'col3': points[:,2]}
points_data = pd.DataFrame(data=d)

data_float.reset_index(inplace=True)
data_float['KM1'] = points_data['col1']
data_float['KM2'] = points_data['col2']
data_float['KM3'] = points_data['col3']
data_float.tail()


fit_predict(X, y=None) me devuelve un array de 68586 con un número que corresponde al cluster al que pertenece cada punto. De la misma forma, puedo acceder a cluster_centers_ y eso es lo que le sumo a cada observacion.
OJO porque si K = 5 entonces le estoy agregando 5 dimensiones a todo esto!!!!

## Verifico cuál es el Koptimo usando Hierarchical 

## Trato de usar PCA

In [17]:
data_float_red = data_float
#data_float_red['PCA1'] = np.zeros(len(data_float_red['rooms']))
#data_float_red['PCA2'] = np.zeros(len(data_float_red['rooms']))
data_float_red

price_aprox_usd  surface_total_in_m2  surface_covered_in_m2  rooms  \
0             700000.00                500.0                  500.0    6.0   
13             98000.00                135.0                  135.0    4.0   
14            430000.00                330.0                  310.0    6.0   
15            270000.00                  0.0                  218.0    4.0   
16             72000.00                 30.0                   30.0    2.0   
17            102000.00                 47.0                   47.0    2.0   
19            189000.00                294.0                  100.0    4.0   
20            145000.00                 79.0                   70.0    3.0   
21            220000.00                 75.0                   65.0    2.0   
22            105000.00                  0.0                   41.0    1.0   
23            142000.00                 47.0                   34.0    1.0   
24            580000.00                354.0                  354.0    5.0   
26            121000.00                  0.0                   65.0    3.0   
27            570000.00                  0.0                  218.0    6.0   
42             95000.00                 38.0                   38.0    2.0   
61            129000.00                 70.0                   70.0    3.0   
80             89000.00                 43.0                   43.0    2.0   
94            880000.00               1680.0                  450.0    8.0   
118           115000.00                182.0                  130.0    4.0   
120           295000.00                140.0                  140.0    5.0   
121           295000.00                140.0                  140.0    5.0   
122           295000.00                140.0                  140.0    5.0   
123            87000.00                 73.0                   70.0    3.0   
124           260000.00                126.0                  119.0    5.0   
125           260000.00                126.0                  119.0    4.0   
190           380000.00                108.0                   79.0    4.0   
192            80000.00                120.0                   80.0    2.0   
197           300000.00                280.0                  160.0    4.0   
198           170000.00                204.0                  145.0    4.0   
204            73000.00                 25.0                   25.0    1.0   
...                 ...                  ...                    ...    ...   
295402        140000.00                 98.0                   98.0    4.0   
295403         90000.00                 65.0                   65.0    3.0   
295408         80000.00                 42.0                   42.0    2.0   
295409        120000.00                160.0                  150.0    3.0   
295410         56000.00                 29.0                   29.0    1.0   
295415        145000.00                130.0                  120.0    3.0   
295416         56083.67                 75.0                   70.0    4.0   
295422        300000.00                220.0                  201.0    4.0   
295424        230000.00                200.0                  185.0    5.0   
295425        130000.00                120.0                  140.0    6.0   
295427        230000.00                125.0                  122.0    3.0   
295432         65000.00                 40.0                   36.0    2.0   
295435         74900.00                 54.0                   36.0    2.0   
295439        160000.00                110.0                  110.0    3.0   
295440         64496.22                 40.0                   40.0    2.0   
295449         85000.00                 43.0                   43.0    3.0   
295450        200000.00                342.0                  160.0    5.0   
295451         80000.00                 35.0                   35.0    2.0   
295452        161500.00                 76.0                   38.0    1.0   
295453        115700.00       

In [25]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
pca.fit(data_float)
red = pca.transform(data_float)
#red
print(pca.singular_values_)

#[  1.02754952e+08   1.91422523e+07   3.11793772e+05]
# el tercer valor singular es considerablemente más chico que los dos anteriores. Por lo tanto trabajo con 
# dos dimensiones

[  1.02754952e+08   1.91422523e+07   3.11793772e+05]


In [26]:
pca = PCA(n_components=2)
pca.fit(data_float)
red = pca.transform(data_float)
print(pca.singular_values_)

[  1.02754952e+08   1.91422523e+07]


In [28]:
red

array([[ 691654.37503471,  133994.95255174],
       [-159638.84515886,  123595.01079413],
       [ 309845.21401464,  129322.35409132],
       ..., 
       [-230982.07099549, -172745.48472993],
       [ 198906.91416304, -167501.27349429],
       [-188558.65316519, -172229.77296627]])

In [27]:
d = {'col1': red[:,0], 'col2': red[:,1]}
red_data = pd.DataFrame(data=d)

data_float.reset_index(inplace=True)
data_float['PCA1'] = red_data['col1']
data_float['PCA2'] = red_data['col2']
data_float.tail()


level_0   index  price_aprox_usd  surface_total_in_m2  \
68581    68581  295459          50000.0                 70.0   
68582    68582  295460          74000.0                 39.0   
68583    68583  295461          45000.0                 27.0   
68584    68584  295462         349000.0                149.0   
68585    68585  295463          75000.0                390.0   

       surface_covered_in_m2  rooms        lat        lon           PCA1  \
68581                  200.0    3.0 -38.030114 -57.574442 -223911.493716   
68582                   39.0    2.0 -38.002849 -57.544908 -189972.937019   
68583                   27.0    1.0 -37.996638 -57.550819 -230982.070995   
68584                  129.0    5.0 -37.099113 -56.840540  198906.914163   
68585                  135.0    4.0 -37.837561 -58.259803 -188558.653165   

                PCA2  
68581 -172657.189361  
68582 -172244.118969  
68583 -172745.484730  
68584 -167501.273494  
68585 -172229.772966

## Intento depurar 'description'

In [4]:
#FILTRO LOS DATOS ANOMALOS

data_float = data.loc[:, ['price_aprox_usd', 'surface_total_in_m2', 'surface_covered_in_m2',\
                          'rooms', 'lat', 'lon', 'description']].dropna()

#filtro
data_float = \
data_float.loc[((data_float.surface_total_in_m2 >= 0.0) & (data_float.surface_total_in_m2 <= 1000000.0)) & \
               ((data_float.surface_covered_in_m2 >= 0.0) & (data_float.surface_covered_in_m2 <= 50000000.0)) & \
               ((data_float.rooms >= 0.0) & (data_float.rooms <= 200.0)), :]


data_float.shape
#(68584, 7)

(68584, 7)

In [20]:
def eraseSpecialCharacters(x):
    result = ''.join(char for char in x if char.isalnum())
    return (result.lower())
                
data_float['descripcion'] = data_float['description']
data_float['descripcion'].apply(eraseSpecialCharacters)
data_float

price_aprox_usd  surface_total_in_m2  surface_covered_in_m2  rooms  \
0             700000.00                500.0                  500.0    6.0   
13             98000.00                135.0                  135.0    4.0   
14            430000.00                330.0                  310.0    6.0   
15            270000.00                  0.0                  218.0    4.0   
16             72000.00                 30.0                   30.0    2.0   
17            102000.00                 47.0                   47.0    2.0   
19            189000.00                294.0                  100.0    4.0   
20            145000.00                 79.0                   70.0    3.0   
21            220000.00                 75.0                   65.0    2.0   
22            105000.00                  0.0                   41.0    1.0   
23            142000.00                 47.0                   34.0    1.0   
24            580000.00                354.0                  354.0    5.0   
26            121000.00                  0.0                   65.0    3.0   
27            570000.00                  0.0                  218.0    6.0   
42             95000.00                 38.0                   38.0    2.0   
61            129000.00                 70.0                   70.0    3.0   
80             89000.00                 43.0                   43.0    2.0   
94            880000.00               1680.0                  450.0    8.0   
118           115000.00                182.0                  130.0    4.0   
120           295000.00                140.0                  140.0    5.0   
121           295000.00                140.0                  140.0    5.0   
122           295000.00                140.0                  140.0    5.0   
123            87000.00                 73.0                   70.0    3.0   
124           260000.00                126.0                  119.0    5.0   
125           260000.00                126.0                  119.0    4.0   
190           380000.00                108.0                   79.0    4.0   
192            80000.00                120.0                   80.0    2.0   
197           300000.00                280.0                  160.0    4.0   
198           170000.00                204.0                  145.0    4.0   
204            73000.00                 25.0                   25.0    1.0   
...                 ...                  ...                    ...    ...   
295402        140000.00                 98.0                   98.0    4.0   
295403         90000.00                 65.0                   65.0    3.0   
295408         80000.00                 42.0                   42.0    2.0   
295409        120000.00                160.0                  150.0    3.0   
295410         56000.00                 29.0                   29.0    1.0   
295415        145000.00                130.0                  120.0    3.0   
295416         56083.67                 75.0                   70.0    4.0   
295422        300000.00                220.0                  201.0    4.0   
295424        230000.00                200.0                  185.0    5.0   
295425        130000.00                120.0                  140.0    6.0   
295427        230000.00                125.0                  122.0    3.0   
295432         65000.00                 40.0                   36.0    2.0   
295435         74900.00                 54.0                   36.0    2.0   
295439        160000.00                110.0                  110.0    3.0   
295440         64496.22                 40.0                   40.0    2.0   
295449         85000.00                 43.0                   43.0    3.0   
295450        200000.00                342.0                  160.0    5.0   
295451         80000.00                 35.0                   35.0    2.0   
295452        161500.00                 76.0                   38.0    1.0   
295453        115700.00       

In [117]:
def eraseSpecialCharacters(x):
    
    import re
    newlabel = re.sub('[^A-Za-z0-9@]+[\:.,:°\-\*]', '', x)
    newlabel = re.sub('[-:]', '', newlabel)
    newlabel = re.sub('[.,]', ' ', newlabel)
    newlabel = newlabel.lower()
    return newlabel
    
string = data_float['description'][0]
resultado = eraseSpecialCharacters(string)
print resultado

venta chalet lote 730 m2 17 32x43 30mts castelar chalet 3 plantas 500mts  cubiertos pb jardín al frente  hall  living comedor  cocina comedor diario  toilette  2 baños completos  lavadero  escritorio  dep  de servicio  garage para 2 autos  quincho  piscina  todos los servicios  fondo libre parquizado 1p 3 dormitorios con placard 1 en suite con vestidor  baño completo 2p playroom oyhanarte propiedades oyhanarte propiedades


In [102]:
print string

Venta - Chalet - LOTE 730 M2 - 17,32x43,30mts. - Castelar.Chalet 3 plantas- 500mts. cubiertos.PB: Jardín al frente, hall, living comedor, cocina comedor diario, toilette, 2 baños completos, lavadero, escritorio, dep. de servicio, garage para 2 autos, quincho, piscina, todos los servicios, fondo libre parquizado.1°P: 3 Dormitorios con placard 1 en suite con vestidor, baño completo.2°P: Playroom.Oyhanarte Propiedades. -  - OYHANARTE PROPIEDADES


In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
